services:
  # Backend API Service
  - type: web
    name: ecoverse-backend
    runtime: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    # Environment variables that need to be set in Render dashboard:
    # GEMINI_API_KEY - for AI functionality

  # Frontend Static Site
  - type: static
    name: ecoverse-frontend
    runtime: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    pullRequestPreviewsEnabled: true
    buildFilter:
      paths:
        - frontend/**
    routes:
      - type: rewrite
        source: /*
        destination: /index.html